apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dvnw3yw8e-nodejs 
  janus-idp.io/tekton: dvnw3yw8e-nodejs
  backstage.io/kubernetes-id: dvnw3yw8e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvnw3yw8e-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  